version: "3.9"

services:
  db:
    image: mysql:8
    container_name: health-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wellflowsyncdb
    ports:
      - "8096:3306"   # MySQL available at localhost:8096
    networks:
      - health-net
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-backend
    ports:
      - "8095:8080"   # Backend available at localhost:8095
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wellflowsyncdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
    depends_on:
      - db
    networks:
      - health-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-frontend
    ports:
      - "8094:8080"   # Frontend available at localhost:8094
    depends_on:
      - backend
    networks:
      - health-net

volumes:
  db-data:

networks:
  health-net:
    driver: bridge
